# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Publish

on:
  push:
    # This will trigger on any tag push
    tags:
      - '*'

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ 22.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create package-lock.json
        shell: sh
        run: |
          cp package.json package-lock.json

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Delete .npmrc
        shell: sh
        run: rm -rf .npmrc

      - name: Install dependencies
        run: npm install

      - name: Mac Publish with npm
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          CSC_LINK: ${{ secrets.MAC_CERT_BASE64 }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}
        run: npm run build:publish

      - name: Windows Publish with npm
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          CSC_LINK: ${{ secrets.WINDOWS_CERT_BASE64 }}
          CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CERT_PASSWORD }}
        run: npm run build:publish

      - name: Linux Publish with npm
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          CSC_LINK: ${{ secrets.LINUX_CERT_BASE64 }}
          CSC_KEY_PASSWORD: ${{ secrets.LINUX_CERT_PASSWORD }}
        run: npm run build:publish
